sonar.projectKey=dven-dev_fastify-web-development-project-6
sonar.organization=dven-dev

sonar.sources=server,src
sonar.tests=__tests__
sonar.exclusions=**/node_modules/**,**/dist/**,**/vendor/**,**/*.pug

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.cpd.exclusions=server/locales/**
